### ISSUE TITLE
Can't install with go

### ISSUE THREAD

**Issue by daudangson** [canta2899/logo-ls#4]
I can't install with go 

![image](https://github.com/canta2899/logo-ls/assets/49583241/3545d786-9735-45d3-9fe1-37f7be816923)

*error*:
```go: github.com/pborman/getopt/v2@v2.0.0: reading github.com/pborman/getopt/go.mod at revision v2.0.0: unknown revision v2.0.0```

**Comment by canta2899** [comment]
Sorry for getting back so late, now it should work using the latest version! Let me know any issue still occours
